window.CONTINENT = {
  i18n: {
    ca: {
      title:   "Mapa interactiu d'Àsia",
      sub:     "Passa el ratolí per sobre de cada país per veure'n el nom, la capital i la bandera.",
      reset:   "Veure tot",
      loading: "Carregant el mapa…",
      foot:    "Mapa per a estudi · països, capitals i banderes d'Àsia",
      search:  "Cerca un país…",
      cap:     "Capital"
    },
    es: {
      title:   "Mapa interactivo de Asia",
      sub:     "Pasa el ratón por encima de cada país para ver su nombre, capital y bandera.",
      reset:   "Ver todo",
      loading: "Cargando el mapa…",
      foot:    "Mapa de estudio · países, capitales y banderas de Asia",
      search:  "Busca un país…",
      cap:     "Capital"
    }
  },
  // clau : [ nom CA, nom ES, capital CA, capital ES, ISO2 ]
  data: {
    "Turkey":               ["Turquia","Turquía","Ankara","Ankara","tr"],
    "Georgia":              ["Geòrgia","Georgia","Tbilisi","Tiflis","ge"],
    "Armenia":              ["Armènia","Armenia","Erevan","Ereván","am"],
    "Azerbaijan":           ["Azerbaidjan","Azerbaiyán","Bakú","Bakú","az"],
    "Syria":                ["Síria","Siria","Damasc","Damasco","sy"],
    "Lebanon":              ["Líban","Líbano","Beirut","Beirut","lb"],
    "Israel":               ["Israel","Israel","Jerusalem","Jerusalén","il"],
    "Jordan":               ["Jordània","Jordania","Amman","Amán","jo"],
    "Iraq":                 ["Iraq","Irak","Bagdad","Bagdad","iq"],
    "Kuwait":               ["Kuwait","Kuwait","Kuwait","Kuwait","kw"],
    "Saudi Arabia":         ["Aràbia Saudita","Arabia Saudí","Riad","Riad","sa"],
    "Yemen":                ["Iemen","Yemen","Sanà","Saná","ye"],
    "Oman":                 ["Oman","Omán","Mascat","Mascate","om"],
    "United Arab Emirates": ["Emirats Àrabs Units","Emiratos Árabes Unidos","Abu Dhabi","Abu Dabi","ae"],
    "Qatar":                ["Qatar","Catar","Doha","Doha","qa"],
    "Iran":                 ["Iran","Irán","Teheran","Teherán","ir"],
    "Kazakhstan":           ["Kazakhstan","Kazajistán","Astanà","Astaná","kz"],
    "Uzbekistan":           ["Uzbekistan","Uzbekistán","Taixkent","Taskent","uz"],
    "Turkmenistan":         ["Turkmenistan","Turkmenistán","Aixkhabad","Asjabad","tm"],
    "Tajikistan":           ["Tadjikistan","Tayikistán","Duixanbé","Dusambé","tj"],
    "Kyrgyzstan":           ["Kirguizistan","Kirguistán","Bixkek","Biskek","kg"],
    "Afghanistan":          ["Afganistan","Afganistán","Kabul","Kabul","af"],
    "Pakistan":             ["Pakistan","Pakistán","Islamabad","Islamabad","pk"],
    "India":                ["Índia","India","Nova Delhi","Nueva Delhi","in"],
    "Nepal":                ["Nepal","Nepal","Katmandú","Katmandú","np"],
    "Bhutan":               ["Bhutan","Bután","Thimphu","Thimphu","bt"],
    "Bangladesh":           ["Bangladesh","Bangladés","Dacca","Daca","bd"],
    "Sri Lanka":            ["Sri Lanka","Sri Lanka","Sri Jayawardenepura Kotte","Sri Jayawardenepura Kotte","lk"],
    "Myanmar":              ["Myanmar","Birmània/Myanmar","Naypyidaw","Naipyidó","mm"],
    "Thailand":             ["Tailàndia","Tailandia","Bangkok","Bangkok","th"],
    "Laos":                 ["Laos","Laos","Vientiane","Vientián","la"],
    "Vietnam":              ["Vietnam","Vietnam","Hanoi","Hanói","vn"],
    "Cambodia":             ["Cambodja","Camboya","Phnom Penh","Nom Pen","kh"],
    "Malaysia":             ["Malàisia","Malasia","Kuala Lumpur","Kuala Lumpur","my"],
    "Brunei":               ["Brunei","Brunéi","Bandar Seri Begawan","Bandar Seri Begawan","bn"],
    "Indonesia":            ["Indonèsia","Indonesia","Jakarta","Yakarta","id"],
    "Philippines":          ["Filipines","Filipinas","Manila","Manila","ph"],
    "Mongolia":             ["Mongòlia","Mongolia","Ulan Bator","Ulán Bator","mn"],
    "China":                ["Xina","China","Pequín","Pekín","cn"],
    "North Korea":          ["Corea del Nord","Corea del Norte","Pyongyang","Pionyang","kp"],
    "South Korea":          ["Corea del Sud","Corea del Sur","Seül","Seúl","kr"],
    "Japan":                ["Japó","Japón","Tòquio","Tokio","jp"],
    "Timor-Leste":          ["Timor Oriental","Timor Oriental","Dili","Dili","tl"]
  },
  alias: {
    "Dem. Rep. Korea":            "North Korea",
    "Korea":                      "South Korea",
    "Republic of Korea":          "South Korea",
    "Lao PDR":                    "Laos",
    "Viet Nam":                   "Vietnam",
    "Brunei Darussalam":          "Brunei",
    "Syrian Arab Republic":       "Syria",
    "Iran (Islamic Republic of)": "Iran",
    "East Timor":                 "Timor-Leste"
  }
};
